import "@/app/globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import PMRSidebarMenu from "@/lib/components/PMRSideMenu";
import { PMRThemeProvider } from "@/lib/components/PMRThemeProvider";
import { LocaleProvider } from "@/lib/contexts/PMRLocaleContext";
import { SidebarProviderClient } from "@/lib/contexts/PMRSidebarContext";
import { SkillsProviderClient } from "@/lib/contexts/PMRSkillsContext";
import ThemeScript from "@/lib/themeScript";
import { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
    weight: "900",
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
    weight: "900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function LocaleLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    const resolvedParams = await params;
    const locale = resolvedParams.locale;
    setRequestLocale(locale);
    const messages = await getMessages();

    return (
        <html lang={locale} suppressHydrationWarning>
            <head>
                <ThemeScript />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextIntlClientProvider messages={messages}>
                    <LocaleProvider initialLocale={locale}>
                        <PMRThemeProvider>
                            <SidebarProvider>
                                <SkillsProviderClient>
                                    <SidebarProviderClient>
                                        <PMRSidebarMenu />
                                    </SidebarProviderClient>
                                    <main className="flex flex-1 flex-col transition-all">
                                        <SidebarTrigger />
                                        {children}
                                    </main>
                                </SkillsProviderClient>
                            </SidebarProvider>
                        </PMRThemeProvider>
                    </LocaleProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
